version: '2'
services:
    dto-app:
        image: dto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dto-postgresql:5432/dto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dto-elasticsearch:9300
        ports:
            - 8080:8080
    dto-postgresql:
        extends:
            file: postgresql.yml
            service: dto-postgresql
    dto-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dto-elasticsearch
